{
 "title": "V2",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Consejeria", "label": "Consejeria" },
   {
    "name": "Servicio",
    "label": "Servicio",
    "query": "INT_PRV_consultaListadoRPAs_v1.0.0,       INT_PRV_CITASCADE_V1.0.0,       INT_PRV_CONSULTA_GASTOS_PAGOS_v1.0.0,       INT_PRV_CONSULTA_GASTOS_PAGOS_DETALLES_v1.0.0,       INT_PRV_CITASTRIBUTARIAS_V1.0.0,       INT_PRV_DIPA_V1.0.0,       INT_PRV_CertificadoAcreditacionCompetencias_v1.0.0,       INT_PRV_TARJETASANITARIA_V1.0.0,       INT_PRV_CITASEVO_V1.0.0,       INT_PRV_TAJ65_v1.0.0,       INT_PRV_CarnetJoven_V1.0.0,       INT_PRV_CartaAdjudicacionRTL_V1.0.0,       INT_PRV_CertificadoProfesionalidad_V1.0.0,       INT_PRV_ConsultaDemDatosDARDE_v1.0.0,       INT_PRV_CitasSAE_v1.0.0,       INT_PRV_CarnetGuiaTuristico_V1.0.0,       INT_PRV_CertificadoDAR_V1.0.0,       INT_PRV_RecuperacionFotografiaGT_v1.0.0,       INT_PRV_GeneracionCertificadoDeportistaRendimiento_v1.0.0,       INT_PRV_CarnetBiblioteca_v1.0.0,       INT_PUB_CONSULTA_LICENCIA_PESCA_CAPDER_V1.0.0,       INT_PUB_CONSULTA_LICENCIA_CAZA_PESCA_CMAOT_V1.0.0,       INT_PUB_CONSULTA_TITULOS_UNIVERSITARIOS_MECD_V1.0.0,       INT_PUB_CONSULTA_TITULOS_NO_UNIVERSITARIOS_MECD_V1.0.0,       INT_PRV_notificacionesCC_JDA_1.8,       INT_PRV_notificacionesCC_AGE_1.3,       INT_PRV_GESTIONDECITAS_V1.0.0,       INT_PRV_CC_COM_ASINCRONA,       INT_PRV_citasPaciente_v1.0,       INT_PRV_citasRadiologia_v1.0"
   },
   { "name": "timeFrom", "query": "1590466000000" },
   { "name": "timeTo", "query": "1590616800000" }
  ]
 },
 "panels": [
  { "title": "Vision general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% Cumplimiento [Alta actividad]",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Disponibilidad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metrics_values",
     "query": "SELECT count(cumpliendo) / (count(nocumpliendo)+count(cumpliendo)) AS Ratio1\nFROM (\nSELECT guaranteeValue as cumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = true AND \"id\" = 'DISPONIBILIDAD_ALTA_ACTIVIDAD'  AND $timeFilter)\n,\n(\nSELECT guaranteeValue as nocumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = false AND \"id\" = 'DISPONIBILIDAD_ALTA_ACTIVIDAD'  AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "id",
       "operator": "=",
       "value": "DISPONIBILIDAD_MAYOR_95_ALTA_ACTIVIDAD"
      }
     ]
    },
    {
     "alias": "Rendimiento",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(cumpliendo) / (count(nocumpliendo)+count(cumpliendo)) AS Ratio1\nFROM (\nSELECT guaranteeValue as cumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = true AND \"id\" = 'TIEMPO_RESPUESTA_ALTA_ACTIVIDAD'  AND $timeFilter)\n,\n(\nSELECT guaranteeValue as nocumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = false AND \"id\" = 'TIEMPO_RESPUESTA_ALTA_ACTIVIDAD'  AND $timeFilter\n)\n\n\n\n\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Disponibilidad (Alta actividad)  [10:00 - 22:00]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_scope_servicio",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "scope_servicio" ], "type": "tag" }
     ],
     "measurement": "metrics_values",
     "select": [
      [
       { "params": [ "guaranteeValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=", "value": "DISPONIBILIDAD_ALTA_ACTIVIDAD" },
      { "condition": "AND", "key": "scope_servicio", "operator": "=~", "value": "/^$Servicio$/" }
     ]
    }
   ]
  },
  {
   "title": "% Cumplimiento [Baja actividad]",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Disponibilidad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metrics_values",
     "query": "SELECT count(cumpliendo) / (count(nocumpliendo)+count(cumpliendo)) AS Ratio1\nFROM (\nSELECT guaranteeValue as cumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = true AND \"id\" = 'DISPONIBILIDAD_BAJA_ACTIVIDAD'  AND $timeFilter)\n,\n(\nSELECT guaranteeValue as nocumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = false AND \"id\" = 'DISPONIBILIDAD_BAJA_ACTIVIDAD' AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "id",
       "operator": "=",
       "value": "DISPONIBILIDAD_MAYOR_95_ALTA_ACTIVIDAD"
      }
     ]
    },
    {
     "alias": "Rendimiento",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(cumpliendo) / (count(nocumpliendo)+count(cumpliendo)) AS Ratio1\nFROM (\nSELECT guaranteeValue as cumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = true AND \"id\" = 'TIEMPO_RESPUESTA_BAJA_ACTIVIDAD'  AND $timeFilter)\n,\n(\nSELECT guaranteeValue as nocumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = false AND \"id\" = 'TIEMPO_RESPUESTA_BAJA_ACTIVIDAD'  AND $timeFilter\n)\n\n\n\n\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Disponibilidad (Baja actividad) [22:00 - 10:00]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_scope_servicio",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "scope_servicio" ], "type": "tag" }
     ],
     "measurement": "metrics_values",
     "select": [
      [
       { "params": [ "guaranteeValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=", "value": "DISPONIBILIDAD_BAJA_ACTIVIDAD" },
      { "condition": "AND", "key": "scope_servicio", "operator": "=~", "value": "/^$Servicio$/" }
     ]
    }
   ]
  },
  {
   "title": "Rendimiento (Alta actividad)  [10:00 - 22:00]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Tiempo de respuesta" }
   ],
   "targets": [
    {
     "alias": "$tag_scope_servicio",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "scope_servicio" ], "type": "tag" }
     ],
     "measurement": "metrics_values",
     "select": [
      [
       { "params": [ "guaranteeValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "id",
       "operator": "=",
       "value": "TIEMPO_RESPUESTA_ALTA_ACTIVIDAD"
      },
      { "condition": "AND", "key": "scope_servicio", "operator": "=~", "value": "/^$Servicio$/" }
     ]
    }
   ]
  },
  {
   "title": "Rendimiento (Baja actividad) [22:00 - 10:00]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Tiempo de respuesta" }
   ],
   "targets": [
    {
     "alias": "$tag_scope_servicio",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "scope_servicio" ], "type": "tag" }
     ],
     "measurement": "metrics_values",
     "select": [
      [
       { "params": [ "guaranteeValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "id",
       "operator": "=",
       "value": "TIEMPO_RESPUESTA_BAJA_ACTIVIDAD"
      },
      { "condition": "AND", "key": "scope_servicio", "operator": "=~", "value": "/^$Servicio$/" }
     ]
    }
   ]
  },
  { "title": "Visualizacion diaria", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Selecciona dia de visualizacion",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "content": "\n<center><input onchange=\"changeTimeSelected(event)\" id=\"daySelector\" type=\"date\"/></center>\n\n<script>\n\n\nconst urlParams = new URLSearchParams(window.location.search);\nvar currentFrom = urlParams.get(\"var-timeFrom\");\nvar currentTo = urlParams.get(\"var-timeTo\");\n\nvar datePickTo;\nvar datePickFrom;\nif (currentFrom && currentTo){\n  datePickFrom = new Date(parseFloat(currentFrom));\n  datePickTo = new Date(parseFloat(currentTo));\n}\nelse{\n  datePickTo = new Date();\n  datePickTo.setHours(0,0,0,0);\n  datePickFrom = new Date(datePickTo.getTime() - 150800000);\n  var newUrl = updateGrafanaVariableAndGetUrl(\"timeFrom\", datePickFrom.getTime());\n  newUrl = updateGrafanaVariableAndGetUrl(\"timeTo\", datePickTo.getTime(), newUrl);\n  setUrl(newUrl);\n}\ndocument.getElementById('daySelector').valueAsDate = datePickFrom;\n\n\n\nfunction updateGrafanaVariableAndGetUrl(variable, value, href){\n  \n    var hash       = {};\n    var parser     = document.createElement('a');\n    var param = \"var-\" + variable;\n\n    parser.href    = href ? href : location.href;\n\n    var parameters = parser.search.split(/\\?|&/);\n\n    for(var i=0; i < parameters.length; i++) {\n        if(!parameters[i])\n            continue;\n\n        var ary      = parameters[i].split('=');\n        hash[ary[0]] = ary[1];\n    }\n\n    hash[param] = value;\n\n    var list = [];  \n    Object.keys(hash).forEach(function (key) {\n        list.push(key + '=' + hash[key]);\n    });\n\n    parser.search = '?' + list.join('&');\n    return parser.href;\n}\n\nfunction setUrl(url){\n  location.href = url;\n}\n\n\nfunction changeTimeSelected(event){\n  var dateSelected = new Date(event.target.value);\n  var timeFrom = dateSelected.getTime();\n  var timeTo = timeFrom + 86400000;\n  console.log(timeFrom + \" - \" + timeTo);\n  var newUrl = updateGrafanaVariableAndGetUrl(\"timeFrom\", timeFrom);\n  newUrl = updateGrafanaVariableAndGetUrl(\"timeTo\", timeTo, newUrl);\n  setUrl(newUrl);\n}\n\n</script>\n\n\n"
  },
  {
   "title": "% Cumplimiento [Alta actividad]",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Disponibilidad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metrics_values",
     "query": "SELECT count(cumpliendo) / (count(nocumpliendo)+count(cumpliendo)) AS Ratio1\nFROM (\nSELECT guaranteeValue as cumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = true AND \"id\" = 'DISPONIBILIDAD_ALTA_ACTIVIDAD' AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms AND \"scope_servicio\" =~ /^$Servicio$/)\n,\n(\nSELECT guaranteeValue as nocumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = false AND \"id\" = 'DISPONIBILIDAD_ALTA_ACTIVIDAD' AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms AND \"scope_servicio\" =~ /^$Servicio$/\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "id",
       "operator": "=",
       "value": "DISPONIBILIDAD_MAYOR_95_ALTA_ACTIVIDAD"
      }
     ]
    },
    {
     "alias": "Rendimiento",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(cumpliendo) / (count(nocumpliendo)+count(cumpliendo)) AS Ratio1\nFROM (\nSELECT guaranteeValue as cumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = true AND \"id\" = 'TIEMPO_RESPUESTA_ALTA_ACTIVIDAD' AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms AND \"scope_servicio\" =~ /^$Servicio$/)\n,\n(\nSELECT guaranteeValue as nocumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = false AND \"id\" = 'TIEMPO_RESPUESTA_ALTA_ACTIVIDAD' AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms AND \"scope_servicio\" =~ /^$Servicio$/ \n)\n\n\n\n\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alta actividad  [22:00 - 10:00]",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 10, "x": 2, "y": 20 },
   "targets": [
    {
     "alias": "Disponibilidad",
     "groupBy": [
      { "params": [ "servicio" ], "type": "tag" }
     ],
     "measurement": "metrics_values",
     "query": "SELECT mean(\"guaranteeValue\") AS \"Disponibilidad\" FROM \"autogen\".\"metrics_values\" WHERE (guaranteeResult = false AND \"id\" = 'DISPONIBILIDAD_ALTA_ACTIVIDAD' AND \"scope_servicio\" =~ /^$Servicio$/) AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms  GROUP BY \"scope_servicio\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disponibilidad" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "id",
       "operator": "=",
       "value": "DISPONIBILIDAD_MAYOR_95_ALTA_ACTIVIDAD"
      },
      { "condition": "AND", "key": "servicio", "operator": "=~", "value": "/^$Servicio$/" }
     ]
    },
    {
     "alias": "Rendimiento",
     "groupBy": [
      { "params": [ "servicio" ], "type": "tag" }
     ],
     "measurement": "metrics_values",
     "query": "SELECT mean(\"guaranteeValue\") AS \"Rendimiento\" FROM \"autogen\".\"metrics_values\" WHERE (guaranteeResult = false AND \"id\" = 'TIEMPO_RESPUESTA_ALTA_ACTIVIDAD' AND \"scope_servicio\" =~ /^$Servicio$/) AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms GROUP BY \"scope_servicio\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rendimiento" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "id",
       "operator": "=",
       "value": "TIEMPO_RESPUESTA_INFERIOR_50_ALTA_ACTIVIDAD"
      },
      { "condition": "AND", "key": "servicio", "operator": "=~", "value": "/^$Servicio$/" },
      { "condition": "AND", "key": "guaranteeResult", "operator": "!=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "% Cumplimiento [Baja actividad]",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Disponibilidad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metrics_values",
     "query": "SELECT count(cumpliendo) / (count(nocumpliendo)+count(cumpliendo)) AS Ratio1\nFROM (\nSELECT guaranteeValue as cumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = true AND \"id\" = 'DISPONIBILIDAD_BAJA_ACTIVIDAD' AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms AND \"scope_servicio\" =~ /^$Servicio$/)\n,\n(\nSELECT guaranteeValue as nocumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = false AND \"id\" = 'DISPONIBILIDAD_BAJA_ACTIVIDAD' AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms AND \"scope_servicio\" =~ /^$Servicio$/\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "id",
       "operator": "=",
       "value": "DISPONIBILIDAD_MAYOR_95_ALTA_ACTIVIDAD"
      }
     ]
    },
    {
     "alias": "Rendimiento",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(cumpliendo) / (count(nocumpliendo)+count(cumpliendo)) AS Ratio1\nFROM (\nSELECT guaranteeValue as cumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = true AND \"id\" = 'TIEMPO_RESPUESTA_BAJA_ACTIVIDAD' AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms AND \"scope_servicio\" =~ /^$Servicio$/)\n,\n(\nSELECT guaranteeValue as nocumpliendo FROM metrics.autogen.metrics_values WHERE guaranteeResult = false AND \"id\" = 'TIEMPO_RESPUESTA_BAJA_ACTIVIDAD' AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms AND \"scope_servicio\" =~ /^$Servicio$/\n)\n\n\n\n\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Baja actividad  [22:00 - 10:00]",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "alias": "Disponibilidad",
     "groupBy": [
      { "params": [ "servicio" ], "type": "tag" }
     ],
     "measurement": "metrics_values",
     "query": "SELECT mean(\"guaranteeValue\") AS \"Disponibilidad\" FROM \"autogen\".\"metrics_values\" WHERE (guaranteeResult = false AND \"id\" = 'DISPONIBILIDAD_BAJA_ACTIVIDAD' AND \"scope_servicio\" =~ /^$Servicio$/ ) AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms GROUP BY \"scope_servicio\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disponibilidad" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "id",
       "operator": "=",
       "value": "DISPONIBILIDAD_MAYOR_90_BAJA_ACTIVIDAD"
      },
      { "condition": "AND", "key": "servicio", "operator": "=~", "value": "/^$Servicio$/" }
     ]
    },
    {
     "alias": "Rendimiento",
     "groupBy": [
      { "params": [ "servicio" ], "type": "tag" }
     ],
     "measurement": "metrics_values",
     "query": "SELECT mean(\"guaranteeValue\") AS \"Rendimiento\" FROM \"autogen\".\"metrics_values\" WHERE (guaranteeResult = false AND \"id\" = 'TIEMPO_RESPUESTA_BAJA_ACTIVIDAD' AND \"scope_servicio\" =~ /^$Servicio$/ ) AND time >= [[timeFrom]]ms AND time <= [[timeTo]]ms  GROUP BY \"scope_servicio\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rendimiento" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "id",
       "operator": "=",
       "value": "TIEMPO_RESPUESTA_INFERIOR_70_BAJA_ACTIVIDAD"
      },
      { "condition": "AND", "key": "servicio", "operator": "=~", "value": "/^$Servicio$/" }
     ]
    }
   ]
  }
 ]
}